version: "3.9"
services:
 hotstarapp:
  build:
   context: .
  container_name: "hotstarapp"
  ports:
   - "8080:8080"
  networks:
   - hotstarapp-nw
 nginx:
  build: ./nginx
  container_name: nginx-server
  ports:
   - "80:80"
  networks:
   - hotstarapp-nw
  depends_on:
   - hotstarapp


networks:
 hotstarapp-nw:
